[project]
authors = ["Mikhail Tavarez <miktavarez@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
description = "A library for playing with colors in Mojo."
name = "hue"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
test = "bash scripts/run_tests.sh"
prepare-tests = "bash scripts/build.sh tests"
package = "bash scripts/build.sh package"
build = "rattler-build build --no-include-recipe"

[dependencies]
max = ">=24.5.0.dev2024083105,<25"
