# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  version: "13.4.2"

package:
  name: "hue"
  version: 0.1.0

source:
  - path: ./src

build:
  script:
    - mkdir -p ${PREFIX}/lib/mojo
    - mojo package hue -o ${PREFIX}/lib/mojo/hue.mojopkg

requirements:
  run:
    - max >= 24.5.0.dev2024083105

# tests:
#   - script:
#       # commands to run to test the package. If any of the commands
#       # returns with an error code, the test is considered failed.
#       - mojo test test/
#       - ls -la info/recipe
#       - cp ${PREFIX}/lib/mojo/hue.mojopkg info/recipe/test/hue.mojopkg
#       - mojo test info/recipe/test/

#     # requirements:
#     #   run:
#     #     - mojo

#     files:
#       # Extra files to be copied to the test directory from the "work directory"
#       source:
#         - ../src/
#         - ../test/

about:
  homepage: https://github.com/thatstoasty/hue
  license: MIT
  license_file: LICENSE
  summary: A library for playing with colors in Mojo.
  repository: https://github.com/thatstoasty/hue
