# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  version: "13.4.2"

package:
  name: "hue"
  version: 0.1.3.nightly

source:
  - path: .
  - path: ../LICENSE
  - path: ../test

build:
  script:
    - mkdir -p ${PREFIX}/lib/mojo
    - magic run mojo package hue
    - cp hue.mojopkg ${PREFIX}/lib/mojo/hue.mojopkg

requirements:
  run:
    - max >= 24.5.0,<25

tests:
  - script:
      # commands to run to test the package. If any of the commands
      # returns with an error code, the test is considered failed.
      # if I don't copy everything into a test dir, mojo test runs the tests in the .magic dir and fails :|
      - mkdir -p test
      - mv test_*.mojo test/
      - mv hue.mojopkg test/
      - magic run mojo test test

    files:
      # Extra files to be copied to the test directory from the "work directory"
      source:
        - hue.mojopkg
        - mojoproject.toml
        - test_*.mojo

about:
  homepage: https://github.com/thatstoasty/hue
  license: MIT
  license_file: LICENSE
  summary: A library for playing with colors in Mojo. https://github.com/thatstoasty/hue
  repository: https://github.com/thatstoasty/hue
