name: Build all packages

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:
#   pull_request:
#     branches:
#       - main
on: ["push"]

jobs:
  build:
    strategy:
      matrix:
        include:
          - { target: linux-64, os: ubuntu-latest }
          - { target: osx-arm64, os: macos-14 }
      fail-fast: false

    runs-on: ${{ matrix.os }}
    timeout-minutes: 5

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install magic
        run: |
          curl -ssL https://magic.modular.com | bash

      - name: Build package for target platform
        env:
          TARGET_PLATFORM: ${{ matrix.target }}

        run: |
          source $HOME/.bash_profile
          magic run build

      - name: Upload all packages
        # do not upload on PR
        if: github.event_name == 'push'
        env:
          PREFIX_API_KEY: ${{ secrets.PREFIX_API_KEY }}
        run: |
          magic run publish
